apiVersion: v1
kind: Service
metadata:
  name: extract-places
spec:
  selector:
    app: extract-places
  type: ClusterIP
  ports:
  - name: http
    port: 5002
    targetPort: 5002 # container
    # nodePort: 30036
    protocol: TCP