apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000 # container
    # nodePort: 30030
    protocol: TCP