apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-plan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-plan
  template:
    metadata:
      labels:
        app: get-plan
    spec:
      containers:
      - name: get-plan
        image: avherrera/getplan_ms:v0.0.2
        ports:
        - containerPort: 5005
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"