apiVersion: v1
kind: Service
metadata:
  name: get-plan
spec:
  selector:
    app: get-plan
  type: ClusterIP
  ports:
  - name: http
    port: 5005
    targetPort: 5005  # container
    # nodePort: 30035
    protocol: TCP