apiVersion: v1
kind: Service
metadata:
  name: get-recomendation
spec:
  selector:
    app: get-recomendation
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 5001  # container
    # nodePort: 30035
    protocol: TCP