apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
    spec:
      containers:
      - name: streamlit-frontend
        image: avherrera/frontend_ms:v1.1.2
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
