apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend
spec:
  selector:
    app: streamlit-frontend
  type: ClusterIP  
  ports:
  - name: http
    port: 8501
    targetPort: 8501 # container
    # nodePort: 30030
    protocol: TCP