services:
  frontend:
    build: ./frontend
    # image: docker.io/avherrera/frontend_ms:v1.1.1
    ports:
      - "8501:8501"
    networks:
      - backend
  get-recomendation:
    # image: docker.io/avherrera/getrecomendation_ms:v1.1
    build: ./get_recomendation
    ports:
      - "5001:5001"
    networks:
      - backend
  extract-places:
    # image: docker.io/avherrera/extractplaces_ms:v1.1
    build: ./extract_places
    ports:
      - "5002:5002"
    networks:
      - backend
  summary-reviews:
    # image: docker.io/avherrera/summaryreviews_ms:v1.1
    build: ./summary_reviews
    ports:
      - "5003:5003"
    networks:
      - backend
  filter:
    build: ./filter
    ports:
      - "5004:5004"
    networks:
      - backend

networks:
  backend:
    driver: bridge