services:
  get_recomendation:
    # image: docker.io/avherrera/get_recomendation_ms:v1.1
    build: ./get_recomendation
    ports:
      - "5001:5001"
    networks:
      - backend
  extract_places:
    # image: docker.io/avherrera/extract_places_ms:v1.1
    build: ./extract_places
    ports:
      - "5002:5002"
    networks:
      - backend
  summary_reviews:
    # image: docker.io/avherrera/summary_reviews_ms:v1.1
    build: ./summary_reviews
    ports:
      - "5003:5003"
    networks:
      - backend

networks:
  backend:
    driver: bridge