services:
  frontend:
    build: ./frontend
    # image: docker.io/avherrera/frontend_ms:v2.2.2
    ports:
      - "3000:3000"
    networks:
      - backend
  get-recomendation:
    # image: docker.io/avherrera/getrecomendation_ms:v2.0.2
    build: ./get_recomendation
    ports:
      - "5001:5001"
    networks:
      - backend
  extract-places:
    # image: docker.io/avherrera/extractplaces_ms:v1.1.4
    build: ./extract_places
    ports:
      - "5002:5002"
    networks:
      - backend
  summary-reviews:
    # image: docker.io/avherrera/summaryreviews_ms:v1.1.4
    build: ./summary_reviews
    ports:
      - "5003:5003"
    networks:
      - backend
  get-plan:
    build: ./get-plan
    image: avherrera/getplan_ms:v0.0.2
    ports:
      - "5005:5005"
    networks:
      - backend

networks:
  backend:
    driver: bridge