# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
#   namespace: cert-manager
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: aleviherrera@gmail.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     # Enable the HTTP-01 challenge provider
#     solvers:
#       - http01:
#           ingress:
#             class: nginx

# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guideplanner
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /   # redirigir trafico
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: guideplanner.pro
    - http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: streamlit-frontend
                port:
                  number: 8501
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /get-recomendation
            pathType: Prefix
            backend:
              service:
                name: get-recomendation
                port:
                  number: 5001
          - path: /extract-places
            pathType: Prefix
            backend:
              service:
                name: extract-places
                port:
                  number: 5002
          - path: /summary-reviews
            pathType: Prefix
            backend:
              service:
                name: summary-reviews
                port:
                  number: 5003
          - path: /filter
            pathType: Prefix
            backend:
              service:
                name: filter
                port:
                  number: 5004
  tls:
    - hosts:
        - guideplanner.pro
      secretName: guideplanner-tls-manual