apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - name: http
    port: 8501
    targetPort: 8501 # container
    # nodePort: 30030
    protocol: TCP