apiVersion: v1
kind: Service
metadata:
  name: summary-reviews
spec:
  selector:
    app: summary-reviews
  type: ClusterIP
  ports:
  - name: http
    port: 5003
    targetPort: 5003 # container
    # nodePort: 30037
    protocol: TCP